Repository LinuxSuRen/api-testing, pull requests merged in 2023-10, with the labels that each got.

#222 feat: support to generate curl command
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/views/TestCase.vue
  pkg/generator/curl_generator.go
  pkg/generator/curl_generator_test.go
  pkg/generator/data/curl.tpl
  pkg/server/remote_server_test.go
  pkg/testing/case.go
  pkg/testing/case_test.go
Labels: enhancement, ui, backend

#225 chore: add http statusCode 422 to the UI locale
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  console/atest-ui/src/locales/en.json
  extensions/store-git/go.mod
  extensions/store-orm/Dockerfie
  go.mod
  go.work.sum
  operator/Dockerfile
  operator/go.mod
Labels: ui, skip-changelog

#223 fix: verify grpc expect body
  pkg/runner/grpc.go
  pkg/runner/grpc_test.go
Labels: bug, glcc, backend

#226 feat: support receving parameters from API
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/views/TestCase.vue
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/server/server_grpc_test.go
  pkg/testing/parser.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader_grpc.pb.go
Labels: enhancement, ui

#233 feat: cache the last selected testcase item in localStorage
  console/atest-ui/src/views/cache.ts
Labels: ui, skip-changelog

#234 fix: cannot get correct value when the header consist mutiple values
  extensions/store-git/go.mod
  go.mod
  go.work.sum
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/util/default.go
  pkg/util/default_test.go
Labels: bug

#235 feat: support releasing api-testing as a Helm chart
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  .gitignore
  Makefile
  docs/README.md
  docs/helm.md
  helm/api-testing/.helmignore
  helm/api-testing/Chart.yaml
  helm/api-testing/templates/NOTES.txt
  helm/api-testing/templates/_helpers.tpl
  helm/api-testing/templates/deployment.yaml
  helm/api-testing/templates/hpa.yaml
  helm/api-testing/templates/ingress.yaml
  helm/api-testing/templates/service.yaml
  helm/api-testing/templates/serviceaccount.yaml
  helm/api-testing/templates/tests/test-connection.yaml
  helm/api-testing/values.yaml
Labels: enhancement

#236 fix: cannot get the correct value when have symbol ;
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  pkg/util/default.go
  pkg/util/default_test.go
Labels: bug, skip-changelog

#238 fix: the helm app version is incorrect
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  Makefile
  cmd/service.go
  go.sum
  go.work.sum
Labels: bug, skip-changelog

#239 [FIXED] grammatical errors in README.md
  docs/README.md
  docs/prometheus.md
Labels: documentation

#240 chore: correct the Helm image path in helm.md
  docs/helm.md
Labels: documentation, skip-changelog

#242 fix: remove redundant empty items from slice and map
  console/atest-ui/src/views/TestCase.vue
  go.work.sum
  pkg/server/remote_server.go
  pkg/util/slice.go
  pkg/util/slice_test.go
Labels: chore, skip-changelog

#243 fix: render the testSuite before generate code
  pkg/server/remote_server.go
Labels: bug, skip-changelog

#244 feat: add pvc setting into the helm chart
  Dockerfile
  Makefile
  console/atest-ui/src/views/TestSuite.vue
  helm/api-testing/Chart.yaml
  helm/api-testing/templates/deployment.yaml
  helm/api-testing/templates/pvc.yaml
  helm/api-testing/templates/service.yaml
  helm/api-testing/values.yaml
  pkg/server/convert.go
  pkg/testing/store.go
  pkg/testing/store_test.go
  pkg/testing/testdata/stores.yaml
Labels: enhancement, backend, skip-changelog

#246 feat: support starting store extentsion automatically
  Makefile
  cmd/server.go
  cmd/server_test.go
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/store.ts
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/store_ext_manager.go
  pkg/server/store_ext_manager_test.go
Labels: enhancement, backend

#248 feat: add SkyWalking support in the Helm chart
  CONTRIBUTION.md
  Dockerfile
  Makefile
  docs/README.md
  docs/helm.md
  extensions/store-git/go.mod
  extensions/store-git/go.sum
  extensions/store-git/main.go
  go.mod
  go.sum
  go.work.sum
  helm/api-testing/templates/deployment.yaml
  helm/api-testing/values.yaml
Labels: enhancement

#249 fix: the variable HELM_REPO in makefile is incorrect
  Makefile
Labels: bug, skip-changelog

#256 docs: fix readme file link error
  README.md
Labels: documentation

#258 feat: add github action to check md link
  .github/workflows/md-link-check.yml
  README.md
  checklink_config.json
Labels: enhancement, chore, skip-changelog

#260 docs: add release notes of v0.0.14 in Chinese
  .github/release-drafter.yml
  docs/release-note-v0.0.13.md
  docs/release-note-v0.0.14.md
Labels: documentation, skip-changelog
