Repository LinuxSuRen/api-testing, pull requests merged in 2023-06, with the labels that each got.

#100 chore: add more info into the releaseDrafter.yaml
  .github/release-drafter.yml
Labels: chore

#99 feat: add some css to the HTML format report
  pkg/runner/data/html.html
  pkg/runner/testdata/report.html
Labels: enhancement

#102 feat: add ui for the api-testing
  .gitignore
  Dockerfile
  Makefile
  README.md
  cmd/function_test.go
  cmd/jsonschema_test.go
  cmd/root.go
  cmd/root_test.go
  cmd/sample_test.go
  cmd/server.go
  cmd/server_test.go
  cmd/service_test.go
  console/atest-ui/.eslintrc.cjs
  console/atest-ui/.gitignore
  console/atest-ui/.prettierrc.json
  console/atest-ui/.vscode/extensions.json
  console/atest-ui/README.md
  console/atest-ui/cypress.config.ts
  console/atest-ui/cypress/e2e/example.cy.ts
  console/atest-ui/cypress/e2e/tsconfig.json
  console/atest-ui/cypress/fixtures/example.json
  console/atest-ui/cypress/support/commands.ts
  console/atest-ui/cypress/support/e2e.ts
  console/atest-ui/env.d.ts
  console/atest-ui/gen.sh
  console/atest-ui/index.html
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/public/favicon.ico
  console/atest-ui/src/App.vue
  console/atest-ui/src/assets/base.css
  console/atest-ui/src/assets/logo.svg
  console/atest-ui/src/assets/main.css
  console/atest-ui/src/main.ts
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/tsconfig.app.json
  console/atest-ui/tsconfig.json
  console/atest-ui/tsconfig.node.json
  console/atest-ui/tsconfig.vitest.json
  console/atest-ui/vite.config.ts
  console/atest-ui/vitest.config.ts
  go.mod
  go.sum
  go.work.sum
  main.go
  pkg/server/http.go
  pkg/server/http_test.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/server/testdata/simple.yaml
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/loader_file_test.go
  pkg/testing/parser_test.go
  sample/answer.yaml
  sample/testsuite-gitee.yaml
Labels: enhancement

#107 feat: show the test cases count in the markdown test report
  pkg/runner/data/report.md
  pkg/runner/writer_markdown_test.go
Labels: enhancement

#111 Proposal accepted in GLCC 2023
  docs/README.md
  docs/glcc-2023-announce.md
Labels: documentation
