Repository LinuxSuRen/api-testing, pull requests merged in 2023-08, with the labels that each got.

#152 chore: put the s3 container into the k8s deploy
  go.work.sum
  sample/kubernetes/default/manifest.yaml
Labels: chore, skip-changelog

#153 fix: the binary atest-store-s3 is missing in docker image
  Dockerfile
Labels: bug, skip-changelog

#154 feat: support generate code from TestCase
  console/atest-ui/src/views/TestCase.vue
  pkg/generator/code_generator.go
  pkg/generator/code_generator_test.go
  pkg/generator/data/main.go.tpl
  pkg/generator/golang_generator.go
  pkg/generator/testdata/expected_go_code.txt
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
Labels: enhancement, ui, backend, generator

#155 fix: the API request from UI missed the header
  console/atest-ui/src/views/APIInput.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/__test__/types.spec.ts
  console/atest-ui/src/views/types.ts
Labels: bug, ui, skip-changelog

#156 fix: should use the specific store in GetSuggestedAPIs
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/testdata/swagger.json
Labels: bug, backend, skip-changelog

#161 feat: support manager store on UI
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/StoreManager.vue
  pkg/server/convert.go
  pkg/server/convert_test.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/loader.go
  pkg/testing/loader_file_test.go
  pkg/testing/parser.go
  pkg/testing/parser_test.go
  pkg/testing/store.go
  pkg/testing/store_test.go
  pkg/testing/testdata/stores.yaml
Labels: enhancement, ui, backend

#158 feat: add operator for maintain the api-testing in Kubernetes
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  .gitignore
  Dockerfile
  Makefile
  README.md
  go.work
  go.work.sum
  operator/.dockerignore
  operator/.gitignore
  operator/Dockerfile
  operator/Makefile
  operator/PROJECT
  operator/README.md
  operator/api/v1alpha1/atest_types.go
  operator/api/v1alpha1/groupversion_info.go
  operator/api/v1alpha1/zz_generated.deepcopy.go
  operator/bundle.Dockerfile
  operator/config/crd/bases/core.linuxsuren.github.com_atests.yaml
  operator/config/crd/kustomization.yaml
  operator/config/crd/kustomizeconfig.yaml
  operator/config/crd/patches/cainjection_in_atests.yaml
  operator/config/crd/patches/webhook_in_atests.yaml
  operator/config/default/kustomization.yaml
  operator/config/default/manager_auth_proxy_patch.yaml
  operator/config/default/manager_config_patch.yaml
  operator/config/manager/kustomization.yaml
  operator/config/manager/manager.yaml
  operator/config/manifests/bases/operator.clusterserviceversion.yaml
  operator/config/manifests/kustomization.yaml
  operator/config/prometheus/kustomization.yaml
  operator/config/prometheus/monitor.yaml
  operator/config/rbac/atest_editor_role.yaml
  operator/config/rbac/atest_viewer_role.yaml
  operator/config/rbac/auth_proxy_client_clusterrole.yaml
  operator/config/rbac/auth_proxy_role.yaml
  operator/config/rbac/auth_proxy_role_binding.yaml
  operator/config/rbac/auth_proxy_service.yaml
  operator/config/rbac/kustomization.yaml
  operator/config/rbac/leader_election_role.yaml
  operator/config/rbac/leader_election_role_binding.yaml
  operator/config/rbac/role.yaml
  operator/config/rbac/role_binding.yaml
  operator/config/rbac/service_account.yaml
  operator/config/samples/core_v1alpha1_atest.yaml
  operator/config/samples/kustomization.yaml
  operator/config/scorecard/bases/config.yaml
  operator/config/scorecard/kustomization.yaml
  operator/config/scorecard/patches/basic.config.yaml
  operator/config/scorecard/patches/olm.config.yaml
  operator/controllers/atest_controller.go
  operator/controllers/configmap.go
  operator/controllers/deployment.go
  operator/controllers/pvc.go
  operator/controllers/service.go
  operator/controllers/suite_test.go
  operator/go.mod
  operator/go.sum
  operator/hack/boilerplate.go.txt
  operator/main.go
Labels: documentation, enhancement, backend

#162 feat: support to generate a PDF report
  .gitignore
  cmd/data/font/.keep
  cmd/data/image/warn.jpg
  cmd/run.go
  go.mod
  go.sum
  pkg/runner/writer_pdf.go
Labels: enhancement, backend

#164 feat: add secret service interface
  .github/testing/core.yaml
  Makefile
  cmd/server.go
  cmd/server_test.go
  docs/README.md
  pkg/render/secret.go
  pkg/render/template.go
  pkg/render/template_test.go
  pkg/secret/types.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/remote/converter_test.go
  pkg/testing/remote/grpc_secret.go
  pkg/testing/remote/grpc_secret_test.go
  pkg/testing/remote/grpc_store.go
  pkg/testing/remote/grpc_store_test.go
  pkg/testing/remote/grpc_test.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader.proto
  pkg/testing/remote/loader_grpc.pb.go
  sample/argocd/simple.yaml
Labels: enhancement, backend, extension

#160 feat: support running gRPC test cases
  cmd/run.go
  docs/api-testing-schema.json
  go.mod
  go.sum
  go.work.sum
  pkg/compare/compare.go
  pkg/compare/compare_test.go
  pkg/compare/error.go
  pkg/compare/error_test.go
  pkg/runner/grpc.go
  pkg/runner/grpc_test.go
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/runner/reporter.go
  pkg/runner/runner.go
  pkg/runner/runner_factory.go
  pkg/runner/verify.go
  pkg/server/remote_server.go
  pkg/testing/case.go
  sample/grpc-sample.yaml
  sample/halo.yaml
  sample/kubernetes.yaml
Labels: enhancement, glcc, backend

#165 feat: add git as the store extension
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  Dockerfile
  Makefile
  README.md
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/TestCase.vue
  docs/README.md
  extensions/store-git/cmd/root.go
  extensions/store-git/cmd/root_test.go
  extensions/store-git/go.mod
  extensions/store-git/go.sum
  extensions/store-git/main.go
  extensions/store-git/pkg/server.go
  go.mod
  go.work
  go.work.sum
  pkg/server/remote_server.go
  pkg/testing/loader_file.go
  pkg/testing/remote/converter.go
  pkg/testing/remote/converter_test.go
  pkg/testing/remote/grpc_store.go
  pkg/util/path.go
  pkg/util/path_test.go
Labels: documentation, enhancement, ui, backend, extension

#166 fix: add unit tests for the git store ext
  Dockerfile
  cmd/service.go
  extensions/store-git/pkg/server.go
  extensions/store-git/pkg/server_test.go
Labels: skip-changelog, test, extension

#167 fix: the store creation dialog state is incorrect
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/StoreManager.vue
Labels: bug, ui, skip-changelog

#168 fix: the test suite data manipulate is not thread safe
  .github/testing/core.yaml
  .github/workflows/build.yaml
  CONTRIBUTION.md
  cmd/run_test.go
  cmd/server.go
  cmd/server_test.go
  docs/manifests/podman.yaml
  pkg/testing/loader_file.go
Labels: bug, backend, skip-changelog

#175 chore: add release note v0.0.13
  Makefile
  cmd/convert.go
  docs/README.md
  docs/release-note-v0.0.13.md
  pkg/generator/converter_jmeter.go
  pkg/generator/converter_jmeter_test.go
  pkg/generator/testdata/expected_jmeter.jmx
  pkg/generator/testdata/expected_testsuite.yaml
  pkg/testing/loader_file.go
  pkg/testing/parser.go
  pkg/testing/parser_test.go
  pkg/util/default.go
  pkg/util/default_test.go
  pkg/util/map_test.go
Labels: skip-changelog

#176 fix: goreleaser build without embed UI
  .github/workflows/release.yaml
  .goreleaser.yaml
  Makefile
  go.sum
Labels: bug, skip-changelog

#179 feat: support importing from Postman
  cmd/convert.go
  cmd/convert_test.go
  cmd/function_test.go
  cmd/testdata/postman.json
  console/atest-ui/src/App.vue
  pkg/generator/importer.go
  pkg/generator/importer_test.go
  pkg/generator/testdata/expected_suite_from_postman.yaml
  pkg/generator/testdata/postman.json
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/server/testdata/postman.json
Labels: ui, backend

#186 ui: support auto saving the test case when sending
  console/atest-ui/src/views/TestCase.vue
Labels: enhancement, ui, to-user

#187 feat: add i18n support for the web ui
  Makefile
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/src/App.vue
  console/atest-ui/src/i18n.ts
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/main.ts
  console/atest-ui/src/views/TemplateFunctions.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
Labels: enhancement, ui, to-user

#188 feat: add more i18n for the UI elements
  console/atest-ui/src/App.vue
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/TestSuite.vue
Labels: ui, skip-changelog

#193 feat: support manage the secrets via UI
  console/atest-ui/src/App.vue
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/SecretManager.vue
  go.work.sum
Labels: ui, to-user

#194 feat: support cache the test case response
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/cache.ts
Labels: enhancement, ui, to-user

#195 feat: support to start plugin in the server sub-cmd
  Makefile
  cmd/server.go
  cmd/service.go
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.proto
  pkg/testing/store.go
  pkg/testing/testdata/stores.yaml
Labels: enhancement, backend, to-user
