Repository LinuxSuRen/api-testing, pull requests merged in 2023-09, with the labels that each got.

#197 feat: auto locate to the last testcase
  cmd/service.go
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/SecretManager.vue
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/cache.ts
Labels: enhancement, ui, to-user

#198 fix: the operator cluster role permission is missing
  operator/config/rbac/role.yaml
  operator/controllers/atest_controller.go
Labels: backend, skip-changelog

#201 fix: the qps feature cannot work well
  .github/workflows/build.yaml
  Makefile
  docs/README.md
  docs/manifests/argocd/simple.yaml
  docs/manifests/kubernetes/default/kustomization.yaml
  docs/manifests/kubernetes/default/manifest.yaml
  docs/manifests/kubernetes/docker.io/kustomization.yaml
  pkg/limit/limiter.go
  pkg/limit/limiter_long_test.go
  pkg/limit/limiter_test.go
Labels: bug, enhancement, backend

#206 fix: missing return in invokeRequest for stream rpc
  .github/testing/core.yaml
  .github/workflows/build.yaml
  pkg/runner/grpc.go
Labels: bug, glcc, backend

#203 fix: cannot save store records
  console/atest-ui/src/views/StoreManager.vue
  pkg/testing/store.go
Labels: bug, ui

#207 Using apache/skywalking-eye to do the license checking work
  .github/workflows/license-check.yaml
  .licenserc.yaml
Labels: chore

#213 add some error handling on the UI
  Makefile
  cmd/server.go
  console/atest-ui/src/App.vue
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/net.ts
  pkg/server/http.go
  pkg/server/remote_server.go
  pkg/util/error.go
  pkg/util/error_test.go
Labels: enhancement, ui

#214 feat: add an expr function httpReady
  cmd/function.go
  cmd/function_test.go
  docs/README.md
  pkg/runner/expr_function.go
  pkg/runner/expr_function_test.go
  pkg/runner/grpc.go
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/testing/parser_test.go
  sample/testsuite-gitlab.yaml
Labels: enhancement, backend

#215 feat: support recording the test results into prometheus
  cmd/run.go
  cmd/run_test.go
  cmd/server.go
  docs/README.md
  docs/prometheus.md
  go.mod
  go.sum
  go.work.sum
  pkg/runner/http.go
  pkg/runner/reporter.go
  pkg/runner/reporter_prometheus.go
  pkg/runner/reporter_prometheus_test.go
Labels: enhancement, backend

#217 add more prometheus metrics
  go.mod
  go.sum
  pkg/runner/reporter_prometheus.go
  pkg/runner/reporter_prometheus_test.go
Labels: backend, skip-changelog

#218 fix: should not parse the response body if it is not JSON format
  cmd/run_test.go
  cmd/server.go
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/util/default.go
Labels: bug

#219 feat: support integrating with skywalking
  .github/workflows/build.yaml
  CONTRIBUTION.md
  Dockerfile
  Makefile
  README.md
  cmd/server.go
  cmd/server_test.go
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/src/App.vue
  console/atest-ui/vite.config.ts
  docs/README.md
  go.mod
  go.sum
  go.work.sum
  main.go
  pkg/server/remote_server.go
Labels: enhancement, backend

#216 feat: get gRPC descriptor from dp set
  .github/testing/grpc_descriptor_set.yaml
  .github/testing/server.pb
  .github/workflows/build.yaml
  .gitignore
  Makefile
  cmd/run.go
  docs/api-testing-schema.json
  docs/grpc-manual-zh.md
  docs/grpc-manual.md
  docs/secure-zh.md
  docs/secure.md
  pkg/runner/grpc.go
  pkg/runner/grpc_test.go
  pkg/runner/grpc_test/server.go
  pkg/runner/grpc_test/test.pb
  pkg/runner/grpc_test/test.pb.go
  pkg/runner/grpc_test/test.proto
  pkg/runner/grpc_test/test_grpc.pb.go
  pkg/runner/grpc_test/testassets/server.key
  pkg/runner/grpc_test/testassets/server.pem
  pkg/runner/http_test.go
  pkg/runner/runner.go
  pkg/runner/runner_test.go
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.proto
  pkg/testing/case.go
  pkg/testing/remote/converter.go
Labels: enhancement, glcc, backend, grpc

#220 feat: support passing skywalking server in podman service
  cmd/service.go
  cmd/service_test.go
Labels: enhancement, skip-changelog

#221 feat: support show the human-readable http status code on ui
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/cache.ts
  pkg/testing/remote/grpc_store.go
Labels: enhancement, ui
