Repository LinuxSuRen/api-testing, pull requests merged in 2023-07, with the labels that each got.

#108 Support maintain testSuite and testCase via UI
  Dockerfile
  Makefile
  README.md
  cmd/server.go
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/TestCase.vue
  go.mod
  pkg/apispec/swagger_test.go
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/case.go
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/loader_file_test.go
  pkg/testing/parser.go
  pkg/testing/parser_test.go
  sample/api-testing-schema.json
  sample/kubernetes/manifest.yaml
Labels: enhancement, ui, backend

#113 feat: support show the response body and header
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/TestCase.vue
  pkg/runner/http.go
  pkg/runner/runner.go
  pkg/server/fake_server.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/server/server_grpc_test.go
  pkg/testing/case.go
  pkg/testing/loader_file.go
  sample/api-testing-schema.json
Labels: enhancement, ui

#116 fix: cannot get the last response when multiple requests happend
  pkg/server/remote_server.go
Labels: skip-changelog

#118 feat: support filter the testcases on the UI
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/TestSuite.vue
Labels: enhancement, ui

#117 feat: embed the ui into the Go binary file
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  Makefile
  cmd/data/index.css
  cmd/data/index.html
  cmd/data/index.js
  cmd/server.go
  cmd/server_test.go
Labels: enhancement

#119 feat: support update and delete testsuite on UI
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/loader_file_test.go
Labels: enhancement

#120 feat: add gRPC loader for reading and writeing test suites
  .dockerignore
  .github/workflows/build.yaml
  .gitignore
  Dockerfile
  Makefile
  cmd/server.go
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  docs/README.md
  extensions/store-etcd/Makefile
  extensions/store-etcd/go.mod
  extensions/store-etcd/go.sum
  extensions/store-etcd/main.go
  extensions/store-etcd/remote/loader.pb.go
  extensions/store-etcd/remote/loader.proto
  extensions/store-etcd/remote/loader_grpc.pb.go
  extensions/store-etcd/server.go
  extensions/store-orm/Dockerfie
  extensions/store-orm/Makefile
  extensions/store-orm/go.mod
  extensions/store-orm/go.sum
  extensions/store-orm/main.go
  extensions/store-orm/pkg/convert.go
  extensions/store-orm/pkg/convert_test.go
  extensions/store-orm/pkg/types.go
  go.work
  go.work.sum
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/parser.go
  pkg/testing/remote/grpc.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader.proto
  pkg/testing/remote/loader_grpc.pb.go
  sonar-project.properties
Labels: enhancement

#121 chore: add api testing for the repo self
  .github/testing/core.yaml
  .github/workflows/build.yaml
  .gitignore
  Makefile
  cmd/server.go
Labels: skip-changelog

#122 feat: support query the popular HTTP headers on UI
  .github/testing/core.yaml
  console/atest-ui/src/views/TestCase.vue
  pkg/server/data/headers.yaml
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader_grpc.pb.go
Labels: enhancement, ui

#126 fix: validation is missing on the testsuite creation UI
  console/atest-ui/src/views/TestSuite.vue
  pkg/testing/loader_file.go
Labels: ui, skip-changelog

#127 feat: support providing the suggested body fields
  console/atest-ui/src/views/TestCase.vue
  go.mod
  go.sum
  pkg/runner/http.go
  pkg/runner/http_test.go
Labels: enhancement, ui

#128 fix: the body fields verify is incorrect with number
  pkg/runner/http.go
  pkg/runner/http_test.go
Labels: skip-changelog

#123 feat: support getting suggested APIs from spec
  .github/pre-commit
  CONTRIBUTION.md
  Dockerfile
  Makefile
  cmd/server.go
  console/atest-ui/src/views/APIInput.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/types.ts
  docs/api-testing-schema.json
  docs/constants.go
  extensions/store-orm/pkg/convert.go
  extensions/store-orm/pkg/convert_test.go
  extensions/store-orm/pkg/types.go
  pkg/runner/reporter_memory_test.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/case.go
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/loader_file_test.go
  pkg/testing/parser.go
  pkg/testing/remote/converter.go
  pkg/testing/remote/grpc.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader.proto
  sample/constants.go
  sample/testsuite-gitee.yaml
Labels: enhancement, ui

#129 test: add unit tests for the UI
  .github/pre-commit
  console/atest-ui/cypress/e2e/example.cy.ts
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/src/App.vue
  console/atest-ui/src/main.ts
  console/atest-ui/src/views/APIInput.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/__test__/types.spec.ts
  console/atest-ui/src/views/types.ts
  console/atest-ui/vitest.config.ts
Labels: skip-changelog, test

#131 feat: support query template functions on UI
  cmd/function.go
  cmd/function_test.go
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/TemplateFunctions.vue
  go.mod
  go.sum
  pkg/render/template.go
  pkg/render/template_test.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
Labels: enhancement, ui

#132 fix: the createFilter func is incorrect
  console/atest-ui/src/views/TestCase.vue
Labels: bug, ui, skip-changelog

#133 feat: add unit tests for UI
  .github/pre-commit
  .github/workflows/build.yaml
  Makefile
  console/atest-ui/cypress/e2e/component-exist.cy.ts
  console/atest-ui/cypress/e2e/example.cy.ts
  console/atest-ui/package.json
Labels: skip-changelog, test

#136 chore: run unit testing on the master
  .github/workflows/release.yaml
  console/atest-ui/cypress/e2e/component-exist.cy.ts
Labels: chore, skip-changelog

#137 chore: add argocd manifest files
  .dockerignore
  Dockerfile
  Makefile
  README.md
  cmd/server.go
  docs/README.md
  sample/argocd/simple.yaml
  sample/kubernetes/kustomization.yaml
  sample/kubernetes/manifest.yaml
Labels: chore, skip-changelog

#138 feat: support start atest as container service
  .github/testing/core.yaml
  cmd/service.go
  cmd/service_test.go
  extensions/collector/pkg/exporter.go
  extensions/collector/pkg/testdata/sample_suite.yaml
  sample/answer.yaml
  sample/halo.yaml
  sample/kubernetes.yaml
  sample/testsuite-gitee.yaml
  sample/testsuite-gitlab.yaml
Labels: enhancement, backend

#139 feat: add parameters in the test suite
  cmd/run.go
  cmd/server.go
  cmd/server_test.go
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/types.ts
  docs/api-testing-schema.json
  extensions/collector/pkg/exporter.go
  pkg/runner/http_test.go
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.proto
  pkg/testing/case.go
  pkg/testing/parser.go
  pkg/testing/parser_test.go
  pkg/testing/remote/converter.go
  pkg/testing/remote/converter_test.go
  pkg/testing/remote/grpc.go
  pkg/testing/remote/grpc_test.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader.proto
  sample/testsuite-gitee.yaml
  sample/testsuite-gitlab.yaml
Labels: enhancement, ui, backend

#140 feat: make podman service start automatically
  cmd/service.go
  cmd/service_test.go
  console/atest-ui/package-lock.json
Labels: enhancement, backend, skip-changelog

#141 docs: add document about the get started
  CONTRIBUTION.md
  cmd/service.go
  docs/README.md
Labels: documentation, skip-changelog

#142 feat: add default local storage mount for container service
  Dockerfile
  cmd/server.go
  cmd/service.go
  cmd/service_test.go
Labels: backend, skip-changelog

#145 feat: support printing the output in real-time
  cmd/service.go
  go.mod
  go.sum
  go.work.sum
Labels: backend, skip-changelog

#146 feat: support building multi-arch container image
  .github/workflows/release.yaml
Labels: chore, skip-changelog

#147 feat: support add multiple stores
  .gitpod.yml
  Makefile
  cmd/root.go
  cmd/root_test.go
  cmd/server.go
  cmd/service.go
  cmd/service/constant.go
  cmd/service_test.go
  console/atest-ui/cypress/e2e/component-exist.cy.ts
  console/atest-ui/src/App.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  docs/README.md
  extensions/store-orm/main.go
  extensions/store-orm/pkg/convert.go
  extensions/store-orm/pkg/convert_test.go
  extensions/store-orm/pkg/types.go
  go.mod
  go.sum
  pkg/server/constant.go
  pkg/server/convert.go
  pkg/server/convert_test.go
  pkg/server/gateway.go
  pkg/server/gateway_test.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/loader_file.go
  pkg/testing/remote/context.go
  pkg/testing/remote/context_test.go
  pkg/testing/remote/converter.go
  pkg/testing/remote/converter_test.go
  pkg/testing/remote/grpc.go
  pkg/testing/remote/grpc_test.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader.proto
  pkg/testing/remote/loader_grpc.pb.go
  pkg/testing/store.go
  pkg/testing/store_test.go
  pkg/testing/testdata/stores.yaml
Labels: enhancement, ui, backend, extension

#148 fix: incorrect heigh setting on UI
  console/atest-ui/src/App.vue
  console/atest-ui/src/assets/main.css
Labels: bug, ui

#149 feat: add introduction process on UI
  console/atest-ui/cypress/e2e/component-exist.cy.ts
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/src/App.vue
  console/atest-ui/src/main.ts
  console/atest-ui/src/views/TemplateFunctions.vue
  docs/README.md
  sample/kubernetes/default/kustomization.yaml
  sample/kubernetes/default/manifest.yaml
  sample/kubernetes/docker.io/kustomization.yaml
  sample/kubernetes/kustomization.yaml
Labels: ui, backend

#150 feat: add bidirectional streaming rpc of functions query
  go.mod
  go.sum
  go.work.sum
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
Labels: enhancement, backend

#151 feat: add s3 storage backend extension
  .github/workflows/build.yaml
  Dockerfile
  Makefile
  README.md
  docs/README.md
  extensions/store-s3/cmd/root.go
  extensions/store-s3/cmd/root_test.go
  extensions/store-s3/go.mod
  extensions/store-s3/go.sum
  extensions/store-s3/main.go
  extensions/store-s3/pkg/fake_s3.go
  extensions/store-s3/pkg/s3_server.go
  extensions/store-s3/pkg/s3_server_test.go
  go.work
  pkg/testing/parser.go
  pkg/testing/remote/context.go
  pkg/testing/remote/converter.go
  pkg/testing/remote/converter_test.go
  pkg/testing/remote/grpc.go
  sample/kubernetes/default/manifest.yaml
Labels: documentation, enhancement, backend, extension
