Repository LinuxSuRen/api-testing, pull requests merged in 2024-09, with the labels that each got.

#526 fix: the new test case request is always empty
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/store.ts
Labels: bug, skip-changelog

#527 fix: the ui loading function is not working
  console/atest-ui/src/views/SecretManager.vue
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/TestingPanel.vue
Labels: bug, skip-changelog

#531 fix: overwrite test case when creating duplicated
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/net.ts
  pkg/testing/loader_file.go
  pkg/testing/loader_file_test.go
Labels: bug

#530 feat: add testcase debug log
  pkg/runner/http.go
  pkg/server/remote_server_test.go
Labels: enhancement, skip-changelog

#532 feat: add download extension store image prefix
  cmd/extension.go
  pkg/downloader/oci.go
  pkg/downloader/store.go
  pkg/server/store_ext_manager.go
Labels: enhancement, ospp

#524 feat: add History api and ui
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/src/App.vue
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestingHistoryPanel.vue
  console/atest-ui/src/views/TestingPanel.vue
  console/atest-ui/src/views/net.ts
  go.work.sum
  pkg/runner/monitor/monitor.pb.go
  pkg/runner/monitor/monitor_grpc.pb.go
  pkg/server/convert.go
  pkg/server/convert_test.go
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server.swagger.json
  pkg/server/server_grpc.pb.go
  pkg/testing/case.go
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/loader_non.go
  pkg/testing/remote/converter.go
  pkg/testing/remote/converter_test.go
  pkg/testing/remote/grpc_store.go
  pkg/testing/remote/grpc_store_test.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader.proto
  pkg/testing/remote/loader_grpc.pb.go
Labels: enhancement, ospp

#534 fix: support view history only in orm store for now
  console/atest-ui/src/views/TestCase.vue
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server.swagger.json
Labels: bug, ui, skip-changelog, ospp

#536 feat: support to show the body size on page
  cmd/server.go
  console/atest-ui/package-lock.json
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/types.ts
  pkg/generator/curl_generator_test.go
  pkg/mock/in_memory.go
  pkg/mock/in_memory_test.go
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/runner/writer_http.go
  pkg/server/remote_server.go
  pkg/util/default.go
Labels: enhancement

#537 chore: support to close message tip
  console/atest-ui/src/views/TestCase.vue
Labels: chore, ui, skip-changelog

#538 feat: support embed file upload
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/store.ts
  console/atest-ui/src/views/types.ts
  pkg/runner/http.go
  pkg/server/remote_server_test.go
  pkg/testing/parser.go
Labels: enhancement

#539 feat: support to import native data
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/TestingPanel.vue
  console/atest-ui/src/views/net.ts
  pkg/generator/importer.go
  pkg/generator/importer_native.go
  pkg/generator/importer_native_test.go
  pkg/generator/importer_test.go
  pkg/generator/testdata/native.json
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/testing/remote/grpc_store.go
Labels: enhancement
