Repository LinuxSuRen/api-testing, pull requests merged in 2024-10, with the labels that each got.

#541 feat: support to upload random image files
  cmd/extension.go
  console/atest-ui/src/views/TemplateFunctions.vue
  console/atest-ui/src/views/TestCase.vue
  go.mod
  go.sum
  go.work.sum
  pkg/generator/curl_generator_test.go
  pkg/render/data/templateUsage.yaml
  pkg/render/image.go
  pkg/render/image_test.go
  pkg/render/pdf.go
  pkg/render/pdf_test.go
  pkg/render/template.go
  pkg/render/template_test.go
  pkg/render/zip.go
  pkg/render/zip_test.go
  pkg/server/convert.go
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.proto
  pkg/testing/case.go
  pkg/testing/case_test.go
  pkg/testing/loader_file.go
  pkg/testing/loader_non.go
  pkg/testing/loader_non_test.go
  pkg/testing/parser.go
  pkg/util/base64.go
Labels: enhancement

#520 refactor: create components of the atest ui
  .github/workflows/release.yaml
  README.md
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/src/components/LoginDialog.vue
  console/atest-ui/src/components/TestSuiteCreationDialog.vue
  console/atest-ui/src/components/TestSuiteImportDialog.vue
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/views/TestingHistoryPanel.vue
  console/atest-ui/src/views/TestingPanel.vue
  console/atest-ui/src/views/__test__/cache.spec.ts
  console/atest-ui/src/views/__test__/common.ts
  console/atest-ui/src/views/__test__/net.spec.ts
  console/atest-ui/src/views/__test__/store.spec.ts
  console/atest-ui/src/views/__test__/types.spec.ts
  console/atest-ui/src/views/net.ts
  pkg/server/store_ext_manager.go
Labels: skip-changelog, test

#545 chore: show server address on the test case page
  console/atest-ui/package-lock.json
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestingPanel.vue
  console/atest-ui/src/views/types.ts
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.proto
Labels: chore, skip-changelog

#546 fix: the grpc connect is incorrect
  e2e/test-suite-common.yaml
  pkg/runner/monitor/monitor.pb.go
  pkg/runner/monitor/monitor_grpc.pb.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server.swagger.json
  pkg/server/server_grpc.pb.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader_grpc.pb.go
Labels: bug, skip-changelog

#548 feat: support to run test case in batch mode
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/net.ts
  console/atest-ui/src/views/store.ts
  go.mod
  pkg/runner/monitor/monitor.pb.go
  pkg/runner/monitor/monitor_grpc.pb.go
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/local/local_secret_service.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader_grpc.pb.go
Labels: enhancement

#551 chore: add project years badge
  README-ZH.md
  README.md
Labels: chore, skip-changelog
