Repository LinuxSuRen/api-testing, pull requests merged in 2024-05, with the labels that each got.

#413 chore: delete package-lock.json
  package-lock.json
Labels: chore, skip-changelog

#414 optimize: optimize makefile and tools
  .github/workflows/build.yaml
  CONTRIBUTION-ZH.md
  CONTRIBUTION.md
  Makefile
  go.work.sum
  helm/api-testing/VERSION
  tools/github-actions/setup-deps/action.yml
  tools/linter/golangci-lint/.golangci.yml
  tools/linter/yamlint/.yamllint
  tools/make/common.mk
  tools/make/docs.mk
  tools/make/env.mk
  tools/make/golang.mk
  tools/make/helm.mk
  tools/make/image.mk
  tools/make/lint.mk
  tools/make/proto.mk
  tools/make/run.mk
  tools/make/test.mk
  tools/make/tools.mk
  tools/make/ui.mk
  tools/src/golangci-lint/go.mod
  tools/src/golangci-lint/go.sum
  tools/src/golangci-lint/pin.go
  tools/src/yamllint/requirements.txt
Labels: chore, skip-changelog

#417 docs: add links between Chinese and English version
  CONTRIBUTING-ZH.md
  CONTRIBUTING.md
  README-ZH.md
  README.md
Labels: documentation, skip-changelog

#418 fix: using a better header struct
  pkg/mock/in_memory.go
  pkg/mock/in_memory_test.go
  pkg/mock/server.go
  pkg/mock/testdata/api.yaml
  pkg/mock/types.go
Labels: enhancement

#421 ci: update release ci yml
  .github/workflows/release-drafter.yml
  .github/workflows/release.yaml
Labels: bug, skip-changelog

#422 fix: Unified helm version number
  helm/api-testing/Chart.lock
  helm/api-testing/VERSION
  tools/make/common.mk
  tools/make/helm.mk
Labels: bug, skip-changelog

#424 fix: ci failure when specifying container registration address
  tools/make/env.mk
  tools/make/helm.mk
  tools/make/image.mk
Labels: bug, skip-changelog

#420 chore: add docker image desc label
  Dockerfile
Labels: chore, skip-changelog

#426 fix: cannot import sub-collection of postman
  pkg/generator/importer.go
  pkg/generator/importer_test.go
  pkg/generator/testdata/expected_suite_from_sub_postman.yaml
  pkg/generator/testdata/postman-sub.json
Labels: bug

#425 feat: support image registry mock server
  cmd/mock.go
  docs/api-testing-schema.json
  docs/mock-server.md
  docs/mock/image-registry.yaml
  pkg/mock/in_memory.go
  pkg/mock/in_memory_test.go
  pkg/mock/testdata/api.yaml
  pkg/mock/types.go
  pkg/render/template.go
  pkg/render/template_test.go
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/util/default.go
Labels: enhancement, backend

#428 feat: add electron based desktop application
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  .gitignore
  console/atest-desktop/README.md
  console/atest-desktop/api.js
  console/atest-desktop/forge.config.js
  console/atest-desktop/index.html
  console/atest-desktop/main.js
  console/atest-desktop/package-lock.json
  console/atest-desktop/package.json
  console/atest-desktop/preload.js
  console/atest-desktop/renderer.js
Labels: enhancement

#429 fix: remove the not found command: tree
  .github/workflows/release.yaml
Labels: bug, skip-changelog

#430 fix: the dir is incorrect for publishing desktop
  .github/workflows/release.yaml
Labels: bug, skip-changelog

#433 fix: missing the npm install during publish
  .github/workflows/release.yaml
Labels: bug, skip-changelog

#434 fix: using powershell on windows
  .github/workflows/release.yaml
Labels: bug, skip-changelog

#435 chore: add macos-13 into the build matrix
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  go.work.sum
Labels: chore, skip-changelog

#437 fix: the win config is incorrect
  console/atest-desktop/README.md
  console/atest-desktop/forge.config.js
Labels: bug, skip-changelog

#431 feat: support send report to a gRPC server
  cmd/run.go
  pkg/runner/grpc.go
  pkg/runner/writer_grpc.go
  pkg/runner/writer_grpc_test.go
  pkg/runner/writer_templates/server.go
  pkg/runner/writer_templates/writer.pb.go
  pkg/runner/writer_templates/writer.proto
  pkg/runner/writer_templates/writer_grpc.pb.go
Labels: enhancement

#438 feat: support to view testSuite as YAML on web page
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/net.ts
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server.swagger.json
  pkg/server/server_grpc.pb.go
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/loader_file_test.go
  pkg/testing/loader_non.go
  pkg/testing/remote/grpc_store.go
Labels: enhancement, ospp

#439 refactor: replace the go model from custom to the official
  cmd/run.go
  go.mod
  go.sum
  go.work.sum
  pkg/apispec/swagger.go
  pkg/apispec/swagger_test.go
  pkg/runner/http.go
Labels: chore, ospp

#445 chore: cp atest to the desktop dir
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  tools/make/desktop.mk
  tools/make/golang.mk
  tools/make/run.mk
  tools/make/ui.mk
Labels: chore, skip-changelog

#443 feat: add view YAML full screen
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/TestSuite.vue
Labels: enhancement, skip-changelog, ospp

#451 fix: error when opening atest-desktop on Windows
  console/atest-desktop/main.js
Labels: bug, ospp

#453 feat: support to return the body string even it is invalid
  .github/workflows/build.yaml
  .github/workflows/qodana_code_quality.yml
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/types.ts
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
Labels: enhancement, skip-changelog

#454 feat: improve the desktop system control features
  .github/workflows/build.yaml
  .gitignore
  console/atest-desktop/api.js
  console/atest-desktop/api.test.js
  console/atest-desktop/forge.config.js
  console/atest-desktop/index.html
  console/atest-desktop/main.js
  console/atest-desktop/package-lock.json
  console/atest-desktop/package.json
  console/atest-desktop/preload.js
  console/atest-desktop/renderer.js
  tools/make/desktop.mk
Labels: enhancement, skip-changelog

#455 feat: support to duplicate test suite and case
  .editorconfig
  .github/workflows/build.yaml
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/MockManager.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/net.ts
  e2e/test-suite-common.yaml
  pkg/runner/http.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/parser.go
Labels: enhancement, ui, backend

#456 chore: add docs style guide links
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING-ZH.md
  CONTRIBUTING.md
Labels: chore, skip-changelog

#457 fix: missing imports in generated golang code fron testcatse #442
  pkg/generator/golang_generator.go
  pkg/generator/testdata/expected_go_code.txt
Labels: bug, skip-changelog, ospp

#458 e2e: add e2e tests for code generators
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build.yaml
  e2e/README.md
  e2e/code-generator/Dockerfile
  e2e/code-generator/JavaScript.sh
  e2e/code-generator/compose.yaml
  e2e/code-generator/curl.sh
  e2e/code-generator/entrypoint.sh
  e2e/code-generator/golang.sh
  e2e/code-generator/java.sh
  e2e/code-generator/python.sh
  e2e/code-generator/start.sh
  e2e/code-generator/test-suites/test-suite.yaml
  pkg/generator/data/main.python.tpl
  pkg/generator/testdata/expected_python_code.txt
  pkg/generator/testdata/expected_python_cookie_request_code.txt
  pkg/generator/testdata/expected_python_form_request_code.txt
Labels: enhancement

#463 fix: avoid exit the main process when plugin start failed
  cmd/server.go
  cmd/server_test.go
  cmd/testdata/stores.yaml
  pkg/server/remote_server_test.go
Labels: bug, skip-changelog

#462 fix: testcase pages show badge question
  console/atest-ui/src/views/TestCase.vue
Labels: bug, ospp

#467 fix: not work when grpc port is a random one
  cmd/server.go
  cmd/server_test.go
  console/atest-desktop/main.js
  e2e/README.md
  pkg/mock/in_memory.go
  pkg/runner/http_test.go
  pkg/server/http.go
  pkg/server/remote_server_test.go
  pkg/util/net.go
Labels: bug, skip-changelog

#468 fix: missing the container exit code check
  e2e/code-generator/start.sh
Labels: bug, skip-changelog
