Repository LinuxSuRen/api-testing, pull requests merged in 2024-06, with the labels that each got.

#465 fix: python generated code error when without HTTP headers
  e2e/code-generator/entrypoint.sh
  e2e/code-generator/test-suites/test-suite.yaml
  pkg/generator/data/main.python.tpl
  pkg/server/remote_server.go
Labels: bug, generator, skip-changelog, ospp

#471 feat: support to download extensions automatically
  Dockerfile
  cmd/extension.go
  cmd/extension_test.go
  cmd/root.go
  cmd/server.go
  console/atest-desktop/main.js
  go.mod
  go.sum
  pkg/downloader/oci.go
  pkg/downloader/oci_test.go
  pkg/downloader/store.go
  pkg/downloader/testdata/registry.yaml
  pkg/mock/in_memory.go
  pkg/server/store_ext_manager.go
  pkg/server/store_ext_manager_test.go
Labels: enhancement

#473 fix: cannot download oci artifact on windows
  .github/workflows/build.yaml
  pkg/downloader/oci.go
  pkg/downloader/oci_test.go
  pkg/downloader/store.go
  pkg/downloader/testdata/registry.yaml
Labels: bug, skip-changelog

#474 chore: improve the home dir getting
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  cmd/run.go
  cmd/server.go
  cmd/service.go
  go.mod
  pkg/server/remote_server.go
  pkg/server/store_ext_manager.go
  pkg/util/home/common.go
  pkg/util/home/darwin.go
  pkg/util/home/doc.go
  pkg/util/home/linux.go
  pkg/util/home/windows.go
Labels: chore, skip-changelog

#475 fix: the file path checking is incorrect on windows
  pkg/testing/loader_file.go
  pkg/testing/parser_test.go
Labels: bug, skip-changelog

#477 feat: add TLS for gRPC server endpoint
  cmd/server.go
  docs/grpc-TLS.md
  e2e/entrypoint.sh
  e2e/openssl.cnf
Labels: enhancement, ospp

#478 feat: support to run test suite via http
  cmd/extension.go
  cmd/extension_test.go
  cmd/server.go
  e2e/compose-k8s.yaml
  e2e/entrypoint.sh
  e2e/k8s.sh
  e2e/start.sh
  e2e/test-suite-common.yaml
  helm/api-testing/templates/deployment.yaml
  helm/api-testing/values.yaml
  pkg/downloader/oci.go
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/server/store_ext_manager.go
Labels: enhancement

#482 fix: fix ci error
  docs/site/assets/atest-vscode.png
  docs/site/content/en/contributions/CONTRIBUTING.md
  docs/site/content/en/latest/tasks/grpc-manual.md
  docs/site/content/zh/contributions/CONTRIBUTING-ZH.md
  docs/site/content/zh/latest/tasks/grpc-TLS.md
  docs/site/content/zh/latest/tasks/grpc-manual-zh.md
  tools/make/docs.mk
Labels: bug, skip-changelog

#481 fix: the docs lint errors
  .github/workflows/docs.yaml
  docs/site/content/en/latest/tasks/prometheus.md
  docs/site/content/en/news/releases/_index.md
  docs/site/content/zh/news/releases/_index.md
Labels: bug, skip-changelog

#486 fix: try to change the site sub-path
  docs/site/hugo.toml
Labels: skip-changelog

#487 fix: the deployment of site has errors
  .github/workflows/docs.yaml
  docs/site/hugo.toml
  docs/site/package.json
Labels: skip-changelog

#485 feat: add serviceMonitor in the helm chart
  helm/api-testing/templates/servicemonitor.yaml
  helm/api-testing/values.yaml
Labels: enhancement, ospp

#484 docs: add release note v0.0.17
  docs/site/content/zh/latest/releases/release-note-v0.0.17.md
Labels: documentation, skip-changelog

#489 docs: fix docs site zh show bug
  docs/site/hugo.toml
Labels: bug, documentation, skip-changelog

#488 feat: add test case execution related promethus metrics
  cmd/server.go
  e2e/test-suite-common.yaml
  go.mod
  pkg/runner/reporter_prometheus.go
  pkg/runner/runner_factory.go
  pkg/runner/verify.go
  pkg/server/remote_server.go
  pkg/testing/case.go
Labels: enhancement

#492 chore: add the codeOwners file
  .github/CODEOWNERS
Labels: chore, skip-changelog

#495 feat: add http requests metrics
  .dockerignore
  .github/workflows/docs.yaml
  cmd/server.go
  e2e/test-suite-common.yaml
  pkg/runner/http_reverse.go
  pkg/server/http.go
Labels: enhancement, skip-changelog

#496 feat: support JSON compaitble contentType parse
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/runner/verify.go
  pkg/runner/verify_test.go
Labels: enhancement

#499 Add JSON schema for mock types
  cmd/server_test.go
  docs/api-testing-mock-schema.json
  docs/constants.go
  pkg/mock/in_memory_test.go
  pkg/mock/reader.go
  pkg/mock/types.go
  pkg/testing/parser.go
Labels: enhancement

#500 chore: add more content-type headers
  .github/workflows/release.yaml
  pkg/server/data/headers.yaml
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
Labels: chore, skip-changelog
