Repository LinuxSuRen/api-testing, pull requests merged in 2024-04, with the labels that each got.

#354 chore: upgrade the app version to be v0.0.15 in helm chart
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  helm/api-testing/Chart.yaml
  operator/Makefile
Labels: skip-changelog

#352 feat: support installing mongodb in the helm chart
  .gitignore
  Makefile
  go.work.sum
  helm/api-testing/Chart.lock
  helm/api-testing/Chart.yaml
  helm/api-testing/templates/deployment.yaml
  helm/api-testing/templates/pvc.yaml
  helm/api-testing/values.yaml
Labels: enhancement, helm

#355 feat: add cookie support for the requesting
  console/atest-ui/src/views/TestCase.vue
  docs/api-testing-schema.json
  go.work.sum
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/server/convert.go
  pkg/server/remote_server_test.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server.swagger.json
  pkg/testing/case.go
Labels: enhancement

#356 fix: the extension cannot run in startup
  cmd/server.go
Labels: bug

#357 docs: add a tech table for the beginner
  CONTRIBUTION.md
Labels: documentation, skip-changelog

#369 feat: support to generator Java code from a HTTP testCase
  pkg/generator/code_generator_test.go
  pkg/generator/data/main.java.tpl
  pkg/generator/java_generator.go
  pkg/generator/testdata/expected_java_code.txt
  pkg/generator/testdata/expected_java_cookie_request_code.txt
  pkg/generator/testdata/expected_java_form_request_code.txt
  pkg/server/remote_server_test.go
Labels: enhancement

#368 feat: add a simple mock server
  README.md
  cmd/mock.go
  cmd/root.go
  go.mod
  go.sum
  pkg/mock/data/api.yaml
  pkg/mock/in_memory.go
  pkg/mock/in_memory_test.go
  pkg/mock/reader.go
  pkg/mock/server.go
  pkg/mock/types.go
Labels: enhancement

#372 chore: create a PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: chore, skip-changelog

#374 chore: add issue template
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature_reuqest.md
  .github/ISSUE_TEMPLATE/non-crash-bug.md
  .github/ISSUE_TEMPLATE/other.md
Labels: chore, skip-changelog

#378 chore: add stale bot
  .github/workflows/stale.yml
Labels: chore, skip-changelog

#375 chore: update the PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: chore, skip-changelog

#381 chore(fix): update issue/config.yml file name
  .github/ISSUE_TEMPLATE/config.yml
Labels: bug, chore, skip-changelog

#385 chore: add license header in the Go code generator
  pkg/generator/data/main.go.tpl
  pkg/generator/testdata/expected_go_code.txt
  pkg/generator/testdata/expected_go_cookie_request_code.txt
  pkg/generator/testdata/expected_go_form_request_code.txt
Labels: chore, skip-changelog

#377 feat: support detailed mock server
  go.mod
  pkg/mock/data/api.yaml
  pkg/mock/in_memory.go
  pkg/mock/in_memory_test.go
  pkg/mock/server.go
  pkg/mock/types.go
Labels: enhancement, backend

#386 chore: fix the pr template file path
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore, skip-changelog

#382 chore: add issue comment github actions
  .github/workflows/issue-comment.yml
Labels: chore

#367 feat: support write the report to a HTTP server
  cmd/run.go
  pkg/runner/writer_http.go
  pkg/runner/writer_http_test.go
  pkg/runner/writer_templates/example.tpl
Labels: enhancement

#389 feat: add logging support
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  Dockerfile
  cmd/run.go
  cmd/server.go
  go.mod
  go.sum
  go.work
  go.work.sum
  operator/go.mod
  operator/go.sum
  pkg/extension/signal.go
  pkg/generator/converter_jmeter.go
  pkg/generator/importer.go
  pkg/logging/log.go
  pkg/logging/log_test.go
  pkg/mock/in_memory.go
  pkg/oauth/github.go
  pkg/oauth/gitlab.go
  pkg/oauth/server.go
  pkg/oauth/user.go
  pkg/runner/expr_function.go
  pkg/runner/grpc.go
  pkg/runner/grpc_test.go
  pkg/runner/http.go
  pkg/runner/kubernetes/client.go
  pkg/runner/reporter_memory.go
  pkg/runner/reporter_prometheus.go
  pkg/runner/writer_github_pr_comment.go
  pkg/runner/writer_pdf.go
  pkg/server/fake.yaml
  pkg/server/fake_server.go
  pkg/server/remote_server.go
  pkg/server/store_ext_manager.go
  pkg/testing/loader_file.go
  pkg/testing/remote/grpc_store.go
  pkg/util/grpc.go
Labels: enhancement

#390 feat: support combine mock and core server together
  cmd/server.go
  cmd/server_test.go
  go.mod
  pkg/mock/in_memory.go
  pkg/mock/in_memory_test.go
  pkg/mock/server.go
  pkg/server/http.go
  pkg/server/http_test.go
Labels: enhancement

#391 chore: add security-related
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/non--crash-security--bug.md
  SECURITY.md
Labels: documentation

#394 chore: update readme & add community-related
  README-ZH.md
  README.md
Labels: documentation, skip-changelog

#398 Support to generator Python code from a HTTP testCase #365
  pkg/generator/code_generator_test.go
  pkg/generator/data/main.python.tpl
  pkg/generator/python_generator.go
  pkg/generator/testdata/expected_python_code.txt
  pkg/generator/testdata/expected_python_cookie_request_code.txt
  pkg/generator/testdata/expected_python_form_request_code.txt
  pkg/server/remote_server_test.go
Labels: enhancement

#379 docs: add code of conduct docs
  CODE_OF_CONDUCT.MD
Labels: documentation

#403 chore: rename CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: chore, skip-changelog

#404 chore(ci): add pull request retest action
  .github/workflows/command.yml
Labels: chore, skip-changelog

#399 fix:Handle gRPC messages larger than max size
  cmd/server.go
  pkg/runner/grpc.go
  pkg/server/remote_server.go
  pkg/server/remote_server_test.go
Labels: bug

#402 feat: support to set the prefix of mock server
  cmd/mock.go
  cmd/server.go
  pkg/mock/in_memory.go
  pkg/mock/in_memory_test.go
  pkg/mock/server.go
  pkg/mock/testdata/api.yaml
Labels: enhancement

#411 fix: the status code not match error ignored
  cmd/server.go
  cmd/server_test.go
  pkg/runner/http.go
  pkg/runner/http_test.go
  pkg/server/remote_server_test.go
Labels: bug, skip-changelog
