Repository LinuxSuRen/api-testing, pull requests merged in 2025-05, with the labels that each got.

#674 docs: add examples of job and template
  docs/site/content/zh/latest/tasks/code-generator.md
  docs/site/content/zh/latest/tasks/extension.md
  docs/site/content/zh/latest/tasks/grpc-TLS.md
  docs/site/content/zh/latest/tasks/grpc-manual.md
  docs/site/content/zh/latest/tasks/job.md
  docs/site/content/zh/latest/tasks/mock.md
  docs/site/content/zh/latest/tasks/secure.md
  docs/site/content/zh/latest/tasks/template.md
  docs/site/content/zh/latest/tasks/verify.md
Labels: documentation, skip-changelog

#675 feat: improve the ui for the larget content view on data mgr
  console/atest-ui/src/views/DataManager.vue
Labels: enhancement, skip-changelog

#678 feat: using code editor instead of input for sql editing
  console/atest-ui/src/views/DataManager.vue
  e2e/code-generator/Dockerfile
Labels: enhancement, skip-changelog

#679 add docker compose extension support
  cmd/compose.go
  cmd/root.go
  cmd/run.go
  docs/site/content/zh/latest/tasks/code-generator.md
  docs/site/content/zh/latest/tasks/e2e.md
  docs/site/content/zh/latest/tasks/testsuite.yaml
  main.go
  pkg/logging/log.go
  pkg/runner/writer.go
  pkg/runner/writer_github_pr_comment.go
  pkg/runner/writer_grpc.go
  pkg/runner/writer_html.go
  pkg/runner/writer_http.go
  pkg/runner/writer_json.go
  pkg/runner/writer_markdown.go
  pkg/runner/writer_pdf.go
  pkg/runner/writer_std.go
  pkg/runner/writer_std_test.go
Labels: enhancement

#693 fix: redis query page issues
  console/atest-ui/src/views/DataManager.vue
Labels: enhancement, ui, skip-changelog

#692 add tcp proxy support
  Dockerfile
  cmd/convert_test.go
  cmd/function_test.go
  cmd/jsonschema_test.go
  cmd/mock-compose.go
  cmd/mock_test.go
  cmd/root_test.go
  cmd/sample_test.go
  cmd/server_test.go
  docs/site/content/zh/latest/tasks/mock.md
  pkg/mock/in_memory.go
  pkg/mock/types.go
  pkg/runner/http_test.go
  pkg/server/store_ext_manager_test.go
  tools/github-actions/setup-deps/action.yml
Labels: enhancement

#702 Fix: (#700) Improve error reporting for Query in fileLoader and nonLoader.
  pkg/testing/loader_file.go
  pkg/testing/loader_non.go
Labels: chore, skip-changelog
