Repository LinuxSuRen/api-testing, pull requests merged in 2025-06, with the labels that each got.

#707 docs: Improve doc formatting and fix linting issues with markdownlint…
  docs/README.md
Labels: documentation, skip-changelog

#708 improving UI of welcome page
  console/atest-ui/src/views/WelcomePage.vue
Labels: enhancement

#711 fix: cannot query data from orm
  console/atest-ui/src/views/DataManager.vue
Labels: bug, skip-changelog

#716 fixed small UI bug of Dark theme
  console/atest-ui/src/assets/base.css
Labels: bug, skip-changelog

#715 feat: add theme swtich support
  cmd/server.go
  console/atest-ui/src/App.vue
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/theme.ts
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/net.ts
  pkg/apispec/remote_swagger.go
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server.swagger.json
  pkg/server/server_grpc.pb.go
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/loader_non.go
  pkg/testing/local/local_secret_service.go
  pkg/testing/remote/grpc_store.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader.proto
  pkg/testing/remote/loader_grpc.pb.go
  pkg/util/home/common.go
Labels: enhancement

#718 feat: support to render the sql as template
  pkg/server/remote_server.go
Labels: enhancement, skip-changelog

#721 feat: support to show the key binding on each page
  console/atest-ui/src/App.vue
  console/atest-ui/src/assets/base.css
  console/atest-ui/src/assets/main.css
  console/atest-ui/src/components/EditButton.vue
  console/atest-ui/src/components/MagicKey.vue
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/DataManager.vue
  console/atest-ui/src/views/SecretManager.vue
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/TemplateFunctions.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/magicKeys.ts
Labels: enhancement, ui

#722 feat: support sql completion for table names
  console/atest-ui/package-lock.json
  console/atest-ui/package.json
  console/atest-ui/src/assets/base.css
  console/atest-ui/src/assets/main.css
  console/atest-ui/src/locales/en.json
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/views/DataManager.vue
  console/atest-ui/src/views/TestCase.vue
Labels: enhancement, ui

#720 fix: switching between zh and en bug
  .gitignore
  console/atest-ui/package-lock.json
  console/atest-ui/src/App.vue
  console/atest-ui/src/locales/zh.json
  console/atest-ui/src/main.ts
  console/atest-ui/src/views/TestSuite.vue
Labels: bug, ospp

#724 chore: add a download link on the webpage
  docs/site/content/zh/_index.md
Labels: chore, skip-changelog

#725 chore: support changing sql dialect
  console/atest-ui/package-lock.json
  console/atest-ui/src/views/DataManager.vue
  console/atest-ui/src/views/store.ts
Labels: chore, skip-changelog

#726 chore: support not show the native sql
  console/atest-ui/src/views/DataManager.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/languageComplete.ts
Labels: chore, skip-changelog

#727 chore: put data manager cache to sessionStorage
  console/atest-ui/src/views/DataManager.vue
  console/atest-ui/src/views/cache.ts
  console/atest-ui/src/views/net.ts
Labels: chore, skip-changelog

#728 feat: support loading key bindings from data file
  console/atest-ui/src/components/MagicKey.vue
  console/atest-ui/src/views/DataManager.vue
  console/atest-ui/src/views/StoreManager.vue
  console/atest-ui/src/views/TestCase.vue
  console/atest-ui/src/views/TestSuite.vue
  console/atest-ui/src/views/magicKeys.ts
  console/atest-ui/src/views/net.ts
  pkg/server/remote_server.go
  pkg/server/server.pb.go
  pkg/server/server.pb.gw.go
  pkg/server/server.proto
  pkg/server/server_grpc.pb.go
  pkg/testing/loader.go
  pkg/testing/loader_file.go
  pkg/testing/loader_non.go
  pkg/testing/remote/grpc_store.go
  pkg/testing/remote/loader.pb.go
  pkg/testing/remote/loader.proto
  pkg/testing/remote/loader_grpc.pb.go
  pkg/util/home/common.go
Labels: enhancement

#732 chore: exclude dependabot in the release draft
  .github/release-drafter.yml
Labels: chore, skip-changelog
